version: '3.8'

services:
  nextjs:
    container_name: frontend
    build: .
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    env_file: .env
    networks:
      - imqdb

networks:
  imqdb:
    external: true